language: php

php:
  - '5.6'

node_js:
  - "4.x"

before_install:
  - npm install -g gulp

install:
  - npm install
  - gulp --production
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

before_script:
  - php artisan key:generate
  - php artisan migrate --seed
  - php artisan db:seed --class=DummyBookmarksSeeder
#  - php -S localhost:8000 -t public/

script:
  - vendor/bin/phpunit
