language: php

php:
  - '5.6'

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - npm install
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed
  - php artisan db:seed --class=DummyBookmarksSeeder
  - wget "https://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar"
  - java -jar selenium-server-standalone-2.48.2.jar
  - sleep 5
#  - php -S localhost:8000 -t public/

script:
  - vendor/bin/phpunit
  - npm test
