version: '2'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
      - MYSQL_ROOT_PASSWORD=rootp4ssword
    ports:
      - "3306:3306"
  app:
    image: debian:jessie
    volumes:
      - .:/app
  web:
    image: rolckers/web-apache-php
    ports:
      - "8000:80"
    depends_on:
      - db
    links:
      - db
    volumes_from:
      - app
  composer:
    image: rolckers/web-apache-php
    entrypoint:
      - composer
    command: --help
    volumes_from:
      - app
  artisan:
    image: rolckers/web-apache-php
    entrypoint:
      - php
      - artisan
    command: --help
    links:
      - db
    volumes_from:
      - app
  npm:
    image: rolckers/web-nodejs
    command: --help
    entrypoint:
      - npm
    volumes_from:
      - app
  gulp:
    image: rolckers/web-nodejs
    command: --help
    entrypoint:
      - gulp
    volumes_from:
      - app
